name: Test and Run Flask Application

on:
  push:
    branches:
      - main # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.6]  # Specify Python versions to test

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run Unit Tests
        env:
          FLASK_ENV: testing  # Optional: Set Flask environment to testing
        run: |
          python -m unittest discover -s . -p "app_unittest.py"  # Adjust if your test filename is different

      - name: Run Flask Application
        env:
          FLASK_APP: app.py
          FLASK_ENV: development  # You can set to 'production' if preferred
        run: |
          flask run --host=0.0.0.0 --port=5000 &
        # Wait for the app to start
        sleep 5

      - name: Check Flask Application Health
        run: |
          curl --fail http://127.0.0.1:5000 || exit 1
